# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: 'TestAgentPool'
  #vmImage: 

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tf-infra'
    backendType: 'azurerm'
    backendServiceArm: 'sadey2k-aks-sp'
    backendAzureRmSubscriptionId: 'c88c8f23-28fa-446c-9737-a0a749bb194f'
    backendAzureRmResourceGroupName: 'sadey2k-backendRG'
    backendAzureRmStorageAccountName: 'sadey2ksa'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tfstate-pipeline-QA'
    allowTelemetryCollection: false

# - task: TerraformCLI@0
#   displayName: Terraform Init
#   inputs:
#     command: 'init'
#     allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform Plan
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tf-infra'
    allowTelemetryCollection: false