# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool: 'TestAgentPool'
  #vmImage: 

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tf-infra'
    backendType: 'azurerm'
    backendServiceArm: 'sadey2k-aks-sp'
    backendAzureRmSubscriptionId: 'c88c8f23-28fa-446c-9737-a0a749bb194f'
    backendAzureRmResourceGroupName: 'backend-rg-DEVELOPMENT'
    backendAzureRmStorageAccountName: 'storagesadedevelopment'
    backendAzureRmContainerName: 'containersade'
    backendAzureRmKey: 'tfstate-pipeline-DEVELOPMENT'
    allowTelemetryCollection: false

- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'plan'
    allowTelemetryCollection: false
    publishPlanResults: 'aks-plan-dev.tf'

- task: TerraformCLI@0
  displayName: Terraform Plam
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/tf-infra'
    allowTelemetryCollection: false